Details popup window
LethaboMot/Port-folio pull request #15
Opened 2023-01-03 19:02 UTC by LethaboMot

in the project I added:

Added CSS
Added javascript
Added images

2023-01-03 22:32 UTC, tufoinnkuo10 requested changes
Hi @LethaboMot 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Mobile popup works as expected


Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/l46CxmW82zcQiRghG/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-01-03 22:32 UTC, tufoinnkuo10 commented on popup.js
> +  source: 'https://github.com/LethaboMot',
- [ ] nice work. please kindly ensure that from mobile screen size of `375` the `seesource` and `seelive `of the mobile version should be well aligned like that of figma version.
yours
![Screenshot (698)_LI](https://user-images.githubusercontent.com/65298048/210450964-cace461e-ab0c-4fbe-8b0c-d679044c31d1.jpg)

2023-01-03 22:32 UTC, tufoinnkuo10 commented on popup.js
>  {
- [ ] please kindly align the link buttons, so it matches the original design for the desktop version
- [ ] kindly put the technologies above the links and align to the right as well. nice work
yours
![Screenshot (699)_LI](https://user-images.githubusercontent.com/65298048/210451659-363e0a7b-2db9-4b0f-8f82-ee7d9a89f920.jpg)
figma 

![Screenshot (691)](https://user-images.githubusercontent.com/65298048/210451749-84cb96fb-5013-4ae2-acfb-4b00520b894a.png)

2023-01-04 14:09 UTC, mikethreels approved these changes
Hi Lethabo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 15:51 UTC, merged